### ISSUE TITLE
Timeout between iterations

### ISSUE THREAD

**Issue by mrluciusfox** [mac-cain13/daemonizable-command#16]
Could you please change the unit of timeout between iterations?
I need a deamon to send for example 30 mails per second, I would like to send an email every iteration and with a timeout in seconds I can't do it!
Thanks!

**Comment by abienvenu** [comment]
You can use decimals :
```php
$this->setTimeout(0.033);
```

**Comment by mrluciusfox** [comment]
You are right! Sorry for the stupid question.
Thanks!
