### ISSUE TITLE
Kill signal not intercepted

### ISSUE THREAD

**Issue by mpoiriert** [mac-cain13/daemonizable-command#26]
Hi,

I am using your daemon command and I am trying to do a proper shut down on kill signal and it doesn't get intercepted.

If I am kiling the script (CTRL-C) from the current command line is working properly but if I am killing it from another window (with a kill command) my shut down code doesn't get executed. I have override the handleSignal to handle more signal but anyway none of them get handle.

```PHP
 public function handleSignal($signal)
    {
        switch ($signal) {
            // Shutdown signals
            case SIGTERM:
            case SIGINT:
            case SIGQUIT:
            case SIGKILL:
                $this->shutdown();
                break;
        }
    }
```

**Comment by mac-cain13** [comment]
Thanks for using this library!

As you can see [over here](https://github.com/mac-cain13/daemonizable-command/blob/master/src/Wrep/Daemonizable/Command/EndlessCommand.php#L56-L64) we only handle `SIGTERM` and `SIGINT`. `SIGINT` is send when you hit CTRL-C, `SIGTERM` is the default when you use `kill`. There even is [a test for handling the termination signal](https://github.com/mac-cain13/daemonizable-command/blob/df8cb3bc00d947aaed96009b4bd0732f56bcca36/tests/Wrep/Daemonizable/Command/EndlessCommandTest.php#L71-L87). So it seems a simple kill should work correctly. `SIGQUIT` doesn't perform any cleanup as described in [this GNU document about termination signals](http://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html).

_Are you sure you aren't sending a `SIGKILL` or `SIGQUIT`?_

If this doesn't solve your problem, could you let me know what command your exactly using on what OS to kill the process?

**Comment by mpoiriert** [comment]
I don't know how/what I tested last week it wasn't working...

Testing now and it's working even with tthe SIGKILL  (kill processid -9, kill processid -3)...

So anyway everything seems to work.

**Comment by mac-cain13** [comment]
Good to hear it's working! 👍
