### ISSUE TITLE
Branch 1.3.0 and 1.3.1 have different symfony dependencies

### ISSUE THREAD

**Issue by marcingy** [mac-cain13/daemonizable-command#28]
I was having an issue with callable type hint that was causing a fatal. I initially started the process of forking the code and then found out that 1.3.1 has the fix. However we are still on symfony 2.x for console but are using dependency injection 3.x. This combination was allowed in 1.3.0 but not in 1.3.1 it looks like 1.3.1 didn't have a correctly updated composer.json file

https://github.com/marcingy/daemonizable-command/tree/branch-1.3.1 fixed in this branch but I have nothing to put a pull request against.

**Comment by mac-cain13** [comment]
I've finally fixed this. Sorry for not responding to your issue.

The new 1.3.2 release should allow Symfony 2.x for console with dependency injection 3.x!

**Comment by marcingy** [comment]
Thank you :)
