### ISSUE TITLE
Can't override EndlessCommand::DEFAULT_TIMEOUT

### ISSUE THREAD

**Issue by acim** [mac-cain13/daemonizable-command#29]
This is used with self::DEFAULT_TIMEOUT and not with static::DEFAULT_TIMEOUT (late static binding), so it can't be overridden.

**Comment by mac-cain13** [comment]
Thanks for using this project!

I'm wondering why you want to override the constant, since it's the `DEFAULT_TIMEOUT` and you can set your own timeout by using `setTimeout` from for example the constructor. What would be the use case of overriding the constant?

**Comment by acim** [comment]
I just think it is more elegant and transparent than always overriding the constructor. This class is made to be inherited, so it should allow such things. Just my opinion.
