### ISSUE TITLE
Does not work on PHP7.1

### ISSUE THREAD

**Issue by inviqa-nmh** [mac-cain13/daemonizable-command#39]
**Versions:**
"symfony/symfony": "2.8.30",
"wrep/daemonizable-command": "1.3"

**Line:**
https://github.com/mac-cain13/daemonizable-command/blob/0dfd00a64b9ff4c7a40acfe638be0448837addac/src/Wrep/Daemonizable/Command/EndlessCommand.php#L216

**Exception:**
```
[Symfony\Component\Debug\Exception\ContextErrorException]                                                                                                                      
  Warning: Declaration of Wrep\Daemonizable\Command\EndlessCommand::setCode(callable $code) should be compatible with Symfony\Component\Console\Command\Command::setCode($code)
```

**Comment by mac-cain13** [comment]
Seems more like a Symfony version issue where the signature of `EndlessComment::setCode` is not compatible with `Command::setCode`. We've done some fixes on this a while ago, could you check if there is a newer version that works for you?

**Comment by r-martins** [comment]
Still have the issue on 3.1.0 with symfony/framework-bundle:5.4.24
