### ISSUE TITLE
Systemd wont start

### ISSUE THREAD

**Issue by nikkii94** [mac-cain13/daemonizable-command#42]
Hello! I have a symfony app with a socket command. I'm using your lib  to run the socket constantly, but and it was working fine for weeks, but suddenly it stopped, and I can't get it work anymore.

Everytime I try to start it I get this:
```
systemctl status -l myapp.service
● myapp.service 
   Loaded: loaded (/etc/systemd/system/myapp.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2019-02-04 10:42:47 CET; 3s ago
  Process: 17029 ExecStart=/home/myapp/symfony/bin/console app:start (code=exited, status=127)
 Main PID: 17029 (code=exited, status=127)

systemd[1]: Unit myapp.service entered failed state.
systemd[1]: myapp.service failed.
```
Here is my myapp.service file:
```
[Unit]
Description=myapp
After=syslog.target

[Service]
ExecStart=/home/myapp/symfony/bin/console app:start
Restart=always
RestartSec=5s

[Install]
WantedBy=multi-user.target
```
Can you help me please? :)

**Comment by mac-cain13** [comment]
What happens if you try to run the command yourself instead of starting it as a service? That would help debug if the problem is with systemd or with the app.

**Comment by mac-cain13** [comment]
Okay, so the problem is with systemd or the way systemd is starting your command. Not with the library.

I see the command exists with errorcode 127, which means something like `command not found`. So maybe some rights or paths changed and give problems?

**Comment by mac-cain13** [comment]
If you can execute `/home/myapp/symfony/bin/console app:start` yourself from any directory and it works, but systemd can't start the service with errorcode 127, it's probably a rights issue.

I can't really help you any further since the library seems to work and I can't look into your setup or system.
