### ISSUE TITLE
Connecting to the daemon 

### ISSUE THREAD

**Issue by wessel-techtribe-nl** [mac-cain13/daemonizable-command#43]
Is there a way to connect to this daemon from the normal Symfony Controllers. I need to store some open sockets because it takes a while to set them up. So the daemon would setup the sockets with socket_create etc and monitor them to stay open.

The webapp would then need to get an open socket from this daemon process.

**Comment by mac-cain13** [comment]
Sorry for the very very late reply, cleaning up some open issues here. :)

There is no communication provided by this library. You have to setup something yourselves, either connecting to a socket on the same machine. Using a message queue to communicate between the two parts of your app or write something to file/the database.
