### ISSUE TITLE
add support for kubernetes probes

### ISSUE THREAD

**Issue by JakubBarta** [mac-cain13/daemonizable-command#44]
Hi, I'd like to thank you for amazing library in the first place!

I'm using `EndlessCommand` in kubernetes and I'd love if it supported k8s' probes (they make sure command is not stuck) - by `touch`ing predefined file every 15 seconds, for example.

My question is - are you interesting in having this new class as a part of this repo?

Thanks for reply @mac-cain13

**Comment by mac-cain13** [comment]
Sorry for the very very late reply, cleaning up some open issues here. :)

I think this could be a good addition to the Readme how to implement this, but it's quite trivial to do yourselves so wouldn't add it as a (sub)class to the lib I think.
