### ISSUE TITLE
[Feature request] Add isShutdownRequested method

### ISSUE THREAD

**Issue by astronom** [mac-cain13/daemonizable-command#51]
I suppose it will be a good feature to add the ability for commands to check if a shutdown was requested, e.g. in finish iteration I have a code that should wait some time to the next iteration, but if I can check that command should be shut down so there is no reason to execute this code. 

If You agree, I can make a PR

**Comment by mac-cain13** [comment]
Sorry for the very very late reply, cleaning up some open issues here. :)

Yes I think it's good to be able to check if shutdown was requested if you do long running operations yourselves. Either being able to read the now private variable or have a method to access that information would be great I think.

Having said that, it still is better to make sure you break up long running operation into smaller batches if possible. That also makes memory leaks more visible and fixes that the shutdown sequence is performed automatically. But there are certainly cases where doing this check is very handy.
