### ISSUE TITLE
Add functionality to Symfony 7

### ISSUE THREAD

**Issue by pieterocp** [mac-cain13/daemonizable-command#54]
In Symfony 6.4.*, the use of the `ContainerAwareInterface` and the `ContainerAwareTrait` is marked as deprecated, to be removed with version 7.

This project uses this in the `EndlessContainerAwareCommand` to clear the entity manager if doctrine is there. This will require changes to work for Symony ^7.0. Their [upgrade guide](https://github.com/symfony/symfony/tree/744d0ac4fa0324a0f92581eb50759b63d3cae257/UPGRADE-7.0.md) suggests using a service subscriber instead.

**Comment by mac-cain13** [comment]
Thanks for the heads up!

Currently I’m not actively maintaining a PHP project at the moment. Would you @pieterocp (or anyone reading this) be able to create a PR for this?

Would love to review/merge that to keep this lib up to date! When it comes down to me I’m not sure when I’m able to implement it myself.

**Comment by pieterocp** [comment]
Sure thing, cooking a couple of PRs, it might end up being a backwards incompatible change to be had + spotted a couple of other bits that could do with adjusting (e.g. few typos, adding in some test cases, travis versions). Hope to brew up a PR (or two) tomorrow.

**Comment by mac-cain13** [comment]
Awesome! 👏 

No problem if this is a backwards incompatible release. Lets keep the API as similar as possible so it’s easy to migrate to the new version.

Think nobody will be happy with having to figure out how the library API changed while in the middle of upgrading your codebase to Symfony 7. :)

Having said that, obviously okay to fix typos and other small things. 👍

**Comment by michnovka** [comment]
Hi, how is this going with the symfony 7 compatibility? Ive seen #55 , was this finished and just untested, or is it abandoned PR? Thanks!

**Comment by mac-cain13** [comment]
@michnovka that PR is mainly untested, would you have time to take it for a spin and report back if it works allright for you? That would give confidence to release it.
